const baseUrl=()=>String(process.env.OPENAI_BASE_URL||'https://coding.gaiaworks.net/openai/v1').replace(/\/+$/,'');
const apiKey=()=>String(process.env.CODEX_API_KEY||process.env.OPENAI_API_KEY||'').trim();
export const MODEL=process.env.OPENAI_MODEL||'gpt-5.5';
export const isAiConfigured=()=>Boolean(apiKey());
export const MODEL_TIMEOUT_MS=Math.max(10000,Number(process.env.OPENAI_TIMEOUT_MS||45000));
function outputText(data){return data.output_text||data.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text||'';}
async function once(input,instructions,schema,schemaName){
 const payload={model:MODEL,store:false,reasoning:{effort:'low'},instructions,input,text:{format:{type:'json_schema',name:schemaName,strict:true,schema}}};
 let response;try{response=await fetch(`${baseUrl()}/responses`,{method:'POST',headers:{Authorization:`Bearer ${apiKey()}`,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(MODEL_TIMEOUT_MS)});}catch(e){if(e.name==='TimeoutError'||e.name==='AbortError')throw new Error(`公司模型在 ${Math.round(MODEL_TIMEOUT_MS/1000)} 秒内未返回结果`);throw new Error(`无法连接公司模型网关：${e.message}`);}
 let data;try{data=await response.json();}catch{throw new Error(`模型网关返回了非 JSON 响应（HTTP ${response.status}）`);}
 if(!response.ok)throw new Error(data.error?.message||`模型网关调用失败（HTTP ${response.status}）`);const text=outputText(data);if(!text)throw new Error('模型未返回结构化内容');try{return JSON.parse(text);}catch{throw new Error('模型返回内容不是有效 JSON');}
}
async function withRetry(input,instructions,schema,schemaName){if(!isAiConfigured())throw new Error('未配置公司模型凭证 CODEX_API_KEY');let last;const started=Date.now();for(let i=0;i<2;i++){try{return {...await once(input,instructions,schema,schemaName),agentMeta:{model:MODEL,attempts:i+1,durationMs:Date.now()-started}};}catch(e){last=e;}}throw new Error(`${last.message}（已重试 1 次）`);}
const demandItem={type:'object',additionalProperties:false,properties:{storeCode:{type:'string'},date:{type:'string'},startTime:{type:'string'},endTime:{type:'string'},role:{type:'string'},requiredCount:{type:'integer'},forecastTraffic:{type:'number'},forecastSales:{type:'number'}},required:['storeCode','date','startTime','endTime','role','requiredCount','forecastTraffic','forecastSales']};
const demandSchema={type:'object',additionalProperties:false,properties:{items:{type:'array',items:demandItem},unresolved:{type:'array',items:{type:'string'}},summary:{type:'string'}},required:['items','unresolved','summary']};
const ruleSchema={type:'object',additionalProperties:false,properties:{items:{type:'array',items:{type:'object',additionalProperties:false,properties:{code:{type:'string',enum:['MONTHLY_HOURS','CONSECUTIVE_DAYS','SKILL_REQUIRED','CROSS_STORE_REQUIRED','TRAVEL_COST_LIMIT']},value:{anyOf:[{type:'number'},{type:'boolean'},{type:'string'}]},confidence:{type:'number'}},required:['code','value','confidence']}},unresolved:{type:'array',items:{type:'string'}},summary:{type:'string'}},required:['items','unresolved','summary']};
const reasonSchema={type:'object',additionalProperties:false,properties:{reasons:{type:'array',items:{type:'object',additionalProperties:false,properties:{employeeId:{type:'string'},reason:{type:'string'}},required:['employeeId','reason']}}},required:['reasons']};
export function normalizeDemandAgentItem(item,metadata,currentYear=new Date().getFullYear()){const rawStore=String(item.storeCode||'').trim(),storeCode=rawStore.replace(/门店$/,'').trim().toUpperCase(),store=metadata.stores.find(s=>String(s.code).toUpperCase()===storeCode||s.name===rawStore);if(!store)throw new Error(`模型返回了不存在的门店“${rawStore||'空'}”`);const rawRole=String(item.role||'').trim(),role=metadata.roles.find(r=>rawRole===r||rawRole.includes(r));if(!role)throw new Error(`模型返回了不存在的岗位“${rawRole||'空'}”`);const rawDate=String(item.date||'').trim(),fullDate=rawDate.match(/^(20\d{2})[-\/]?(\d{1,2})[-\/](\d{1,2})$/)||rawDate.match(/^(20\d{2})年(\d{1,2})月(\d{1,2})日$/),shortDate=rawDate.match(/^(\d{1,2})月(\d{1,2})日$/),parts=fullDate?[fullDate[1],fullDate[2],fullDate[3]]:shortDate?[String(currentYear),shortDate[1],shortDate[2]]:null,date=parts?`${parts[0]}-${parts[1].padStart(2,'0')}-${parts[2].padStart(2,'0')}`:'';if(!date||Number.isNaN(Date.parse(`${date}T00:00:00Z`)))throw new Error(`模型返回的日期“${rawDate||'空'}”无效`);const time=(value,label)=>{const raw=String(value||'').trim(),match=raw.match(/^(\d{1,2})(?:[:：](\d{1,2})|点(?:(\d{1,2})分?)?)$/),hour=Number(match?.[1]),minute=Number(match?.[2]||match?.[3]||0);if(!match||hour>23||minute>59)throw new Error(`模型返回的${label}“${raw||'空'}”无效`);return `${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`},startTime=time(item.startTime,'开始时间'),endTime=time(item.endTime,'结束时间'),requiredCount=Number(item.requiredCount);if(!Number.isInteger(requiredCount)||requiredCount<1)throw new Error(`模型返回的需求人数“${item.requiredCount}”无效`);if(startTime>=endTime)throw new Error('模型返回的结束时间必须晚于开始时间');return {storeId:store.id,date,startTime,endTime,role,requiredCount,forecastTraffic:Number(item.forecastTraffic||0),forecastSales:Number(item.forecastSales||0),source:'agent'};}
export async function parseRulesWithAgent(text,metadata){return withRetry(`用户规则：${text}\n系统元数据：${JSON.stringify(metadata)}`,'你是WFM规则配置Agent。只抽取明确规则，不创造门店或数字。',ruleSchema,'wfm_rule_parse');}
export async function explainCandidates(context){const result=await withRetry(JSON.stringify(context),'你是WFM补位推荐解释Agent。只能使用输入数字，不能改分数或合规结论。',reasonSchema,'wfm_candidate_reasons');return {reasons:Object.fromEntries(result.reasons.map(x=>[x.employeeId,x.reason]))};}
export async function parseDemandWithAgent(text,metadata){return withRetry(`主管业务输入：${text}\n可用元数据：${JSON.stringify(metadata)}`,'你是WFM业务需求理解Agent。将每个岗位及其人数拆成独立items，并共享用户明确表达的门店、日期、时段、客流和销售上下文。禁止创造门店、岗位或数字；未提供的信息写入unresolved。门店和岗位只能来自元数据。',demandSchema,'wfm_demand_parse');}
