import test from 'node:test';
import assert from 'node:assert/strict';
import { createDatabase,resetDatabase } from './db.mjs';
import { deterministicParse,saveDraft,activateDraft,activeRules,createShortage,recommend,confirmSuggestion,optimizeRules,decideOptimization,dashboard } from './ai-native-engine.mjs';

test('重置幂等并生成真实演示数据',()=>{const db=createDatabase(':memory:');resetDatabase(db);resetDatabase(db);assert.deepEqual(dashboard(db),{stores:3,employees:9,activeRules:5,openShortages:0,confirmedTransfers:0,totalCost:0});});
test('规则解析阻止不存在的D门店激活',()=>{const db=createDatabase(':memory:');const parsed=deterministicParse('D门店月工时不超过170小时',db);assert.deepEqual(parsed.unresolved,['D门店不存在，需要人工确认']);const draft=saveDraft(db,'D门店月工时不超过170小时',parsed);assert.throws(()=>activateDraft(db,draft.id),/待确认/);});
test('规则激活生成新版本',()=>{const db=createDatabase(':memory:');const draft=saveDraft(db,'月工时不超过170小时',deterministicParse('月工时不超过170小时',db));activateDraft(db,draft.id);const rule=activeRules(db).find(x=>x.code==='MONTHLY_HOURS');assert.equal(rule.value,170);assert.equal(rule.version,2);});
test('缺口推荐执行确定性过滤并计算可读依据',()=>{const db=createDatabase(':memory:');const s=createShortage(db,{storeId:'store-a',role:'收银',startAt:'2026-08-08T09:00:00Z',endAt:'2026-08-08T17:00:00Z',headcount:2});const result=recommend(db,s.id);assert.equal(result.filterSummary.总候选,8);assert.ok(result.filterSummary.技能不符>=1);assert.ok(result.filterSummary.无跨店资格>=1);assert.ok(result.suggestions.length>=2);assert.match(result.suggestions[0].reason,/月工时/);});
test('确认调剂实时计算合规与成本分摊',()=>{const db=createDatabase(':memory:');const s=createShortage(db,{storeId:'store-a',role:'收银',startAt:'2026-08-08T09:00:00Z',endAt:'2026-08-08T17:00:00Z',headcount:2});const result=recommend(db,s.id);const confirmed=confirmSuggestion(db,result.suggestions[0].id);assert.equal(confirmed.passed,true);assert.match(confirmed.cost.formula,/8小时/);assert.equal(dashboard(db).confirmedTransfers,1);});
test('规则变化使旧推荐失效并自动重新推荐',()=>{const db=createDatabase(':memory:');const s=createShortage(db,{storeId:'store-a',role:'收银',startAt:'2026-08-08T09:00:00Z',endAt:'2026-08-08T17:00:00Z',headcount:2});const result=recommend(db,s.id);const target=result.suggestions.find(x=>x.monthly_hours>=164);assert.ok(target);const draft=saveDraft(db,'月工时不超过170小时',deterministicParse('月工时不超过170小时',db));activateDraft(db,draft.id);const confirmation=confirmSuggestion(db,target.id);assert.equal(confirmation.passed,false);assert.match(confirmation.message,/自动重新推荐/);});
test('规则优化必须人工采纳后才生成新版本',()=>{const db=createDatabase(':memory:');const before=activeRules(db).find(x=>x.code==='MONTHLY_HOURS');const o=optimizeRules(db);assert.equal(activeRules(db).find(x=>x.code==='MONTHLY_HOURS').version,before.version);decideOptimization(db,o.id,true);assert.equal(activeRules(db).find(x=>x.code==='MONTHLY_HOURS').version,before.version+1);});
