import { randomUUID, createHash } from 'node:crypto';
import { parseJson, transaction } from './db.mjs';
import { activeRules, err } from './ai-native-engine.mjs';

const now=()=>new Date().toISOString();
const j=x=>JSON.stringify(x);
const hours=(a,b)=>(new Date(b)-new Date(a))/3600000;
const overlap=(a1,a2,b1,b2)=>new Date(a1)<new Date(b2)&&new Date(b1)<new Date(a2);
const dateTime=(date,time)=>`${date}T${time}:00.000Z`;
const ruleMap=db=>Object.fromEntries(activeRules(db).map(r=>[r.code,r]));
export function listEmployees(db){return db.prepare('SELECT e.*,s.name store_name FROM employees e JOIN stores s ON s.id=e.store_id ORDER BY e.code').all().map(e=>({...e,skills:parseJson(e.skills_json,[]),preference:parseJson(e.preference_json,{})}));}
export function saveEmployee(db,b,id=randomUUID()){
 const exists=db.prepare('SELECT 1 FROM employees WHERE id=?').get(id);const fields=[String(b.code||''),String(b.name||''),b.storeId,j(b.skills||[]),b.crossStore?1:0,Number(b.monthlyHours||0),Number(b.consecutiveDays||0),Number(b.hourlyRate||0),Number(b.travelCost||0),b.available===false?0:1,Number(b.contractHours||160),j(b.preference||{}),b.status||'active'];if(!fields[0]||!fields[1]||!fields[2])throw err('工号、姓名和门店为必填项');if(exists)db.prepare('UPDATE employees SET code=?,name=?,store_id=?,skills_json=?,cross_store=?,monthly_hours=?,consecutive_days=?,hourly_rate=?,travel_cost=?,available=?,contract_hours=?,preference_json=?,status=? WHERE id=?').run(...fields,id);else db.prepare('INSERT INTO employees VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,...fields);return listEmployees(db).find(e=>e.id===id);
}
export function listLeaves(db){return db.prepare('SELECT l.*,e.name employee_name,e.code employee_code FROM leave_requests l JOIN employees e ON e.id=l.employee_id ORDER BY l.requested_at DESC').all();}
export function createLeave(db,b){if(!b.employeeId||!b.startAt||!b.endAt)throw err('员工和请假时间为必填项');const id=randomUUID();db.prepare('INSERT INTO leave_requests VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,b.employeeId,b.leaveType||'事假',b.startAt,b.endAt,b.reason||'',b.status||'pending',now(),b.status==='approved'?now():null,b.note||null);return db.prepare('SELECT * FROM leave_requests WHERE id=?').get(id);}
export function decideLeave(db,id,status,note=''){if(!['approved','rejected','cancelled'].includes(status))throw err('请假状态无效');db.prepare('UPDATE leave_requests SET status=?,decided_at=?,decision_note=? WHERE id=?').run(status,now(),note,id);return db.prepare('SELECT * FROM leave_requests WHERE id=?').get(id);}
export function calendar(db,start,end){return db.prepare('SELECT * FROM calendar_days WHERE date BETWEEN ? AND ? ORDER BY date').all(start,end);}
export function listDemands(db,start,end,storeId){let sql='SELECT d.*,s.name store_name FROM business_demands d JOIN stores s ON s.id=d.store_id WHERE d.demand_date BETWEEN ? AND ?',args=[start,end];if(storeId){sql+=' AND d.store_id=?';args.push(storeId)}return db.prepare(sql+' ORDER BY d.demand_date,d.start_time,d.role').all(...args);}
export function saveDemand(db,b,id=randomUUID()){let exists=db.prepare('SELECT 1 FROM business_demands WHERE id=?').get(id);if(!exists){const same=db.prepare('SELECT id FROM business_demands WHERE store_id=? AND demand_date=? AND start_time=? AND end_time=? AND role=?').get(b.storeId,b.date,b.startTime,b.endTime,b.role);if(same){id=same.id;exists=true}}const values=[b.storeId,b.date,b.startTime,b.endTime,b.role,Number(b.requiredCount),Number(b.forecastTraffic||0),Number(b.forecastSales||0),b.source||'manual','confirmed',now()];if(!b.storeId||!b.date||!b.role||!b.requiredCount)throw err('门店、日期、岗位和需求人数为必填项');if(exists)db.prepare('UPDATE business_demands SET store_id=?,demand_date=?,start_time=?,end_time=?,role=?,required_count=?,forecast_traffic=?,forecast_sales=?,source=?,status=?,created_at=? WHERE id=?').run(...values,id);else db.prepare('INSERT INTO business_demands VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,...values);return db.prepare('SELECT * FROM business_demands WHERE id=?').get(id);}
export function parseDemandText(text,db){const store=[...db.prepare('SELECT * FROM stores').all()].find(s=>text.includes(s.code+'门店')||text.includes(s.name))||db.prepare("SELECT * FROM stores WHERE code='A'").get();const date=text.match(/(2026-\d{2}-\d{2}|8月(\d{1,2})日)/);const iso=date?.[1]?.startsWith('2026')?date[1]:date?.[2]?`2026-08-${date[2].padStart(2,'0')}`:'2026-08-08';const role=['收银','导购','理货'].find(x=>text.includes(x))||'收银';const count=Number(text.match(/(?:缺|需要|安排)(\d+)人/)?.[1]||text.match(/(\d+)名/)?.[1]||2);const time=text.match(/(\d{1,2})[:：点](\d{2})?.*?(\d{1,2})[:：点](\d{2})?/);return [{storeId:store.id,date:iso,startTime:time?`${time[1].padStart(2,'0')}:${time[2]||'00'}`:'09:00',endTime:time?`${time[3].padStart(2,'0')}:${time[4]||'00'}`:'17:00',role,requiredCount:count,forecastTraffic:Number(text.match(/客流[^0-9]*(\d+)/)?.[1]||0),forecastSales:Number(text.match(/销售[^0-9]*(\d+)/)?.[1]||0),source:'agent'}];}
function signature(db,weekStart,storeId){const rows=[...db.prepare('SELECT id,monthly_hours,consecutive_days,available,skills_json FROM employees ORDER BY id').all(),...db.prepare("SELECT id,status,start_at,end_at FROM leave_requests WHERE status='approved' ORDER BY id").all(),...db.prepare('SELECT id,start_at,end_at,employee_id FROM shifts ORDER BY id').all(),...activeRules(db).map(r=>({id:r.id,version:r.version}))];return createHash('sha256').update(j({weekStart,storeId,rows})).digest('hex');}
export function validateShift(db,b,excludeId=null){const employee=db.prepare('SELECT * FROM employees WHERE id=?').get(b.employeeId);if(!employee)throw err('员工不存在',404);const rules=ruleMap(db),duration=hours(b.startAt,b.endAt),hard=[],soft=[];if(!parseJson(employee.skills_json,[]).includes(b.role))hard.push({code:'SKILL_REQUIRED',message:`${employee.name}不具备${b.role}技能`});const leave=db.prepare("SELECT * FROM leave_requests WHERE employee_id=? AND status='approved'").all(b.employeeId).find(x=>overlap(b.startAt,b.endAt,x.start_at,x.end_at));if(leave)hard.push({code:'APPROVED_LEAVE',message:`与已批准${leave.leave_type}冲突`});const shifts=db.prepare('SELECT * FROM shifts WHERE employee_id=?').all(b.employeeId).filter(x=>x.id!==excludeId);if(shifts.some(x=>overlap(b.startAt,b.endAt,x.start_at,x.end_at)))hard.push({code:'SHIFT_OVERLAP',message:'与已有班次时间重叠'});if(employee.monthly_hours+duration>rules.MONTHLY_HOURS.value)hard.push({code:'MONTHLY_HOURS',message:`预计月工时${employee.monthly_hours+duration}小时，超过${rules.MONTHLY_HOURS.value}小时`});if(employee.store_id!==b.storeId&&!employee.cross_store)hard.push({code:'CROSS_STORE_REQUIRED',message:'员工无跨店资格'});if(employee.consecutive_days+1>rules.CONSECUTIVE_DAYS.value)hard.push({code:'CONSECUTIVE_DAYS',message:'连续工作天数超过上限'});if(employee.travel_cost>rules.TRAVEL_COST_LIMIT.value)soft.push({code:'TRAVEL_COST_LIMIT',message:`交通成本${employee.travel_cost}元超过建议值${rules.TRAVEL_COST_LIMIT.value}元`});const pref=parseJson(employee.preference_json,{}).preferredShift;if(pref==='morning'&&new Date(b.startAt).getUTCHours()>=13)soft.push({code:'PREFERENCE',message:'不符合员工早班偏好'});return {passed:hard.length===0,hardConflicts:hard,softConflicts:soft,duration};}
const weights={balanced:{cost:1,fairness:.6,preference:6,cross:8},cost:{cost:2,fairness:.2,preference:2,cross:14},experience:{cost:.5,fairness:1.2,preference:14,cross:4}};
export function generatePlans(db,{storeId,weekStart}){const end=new Date(`${weekStart}T00:00:00Z`);end.setUTCDate(end.getUTCDate()+6);const demands=listDemands(db,weekStart,end.toISOString().slice(0,10),storeId);if(!demands.length)throw err('当前周没有已确认业务需求');const employees=listEmployees(db),rules=Object.fromEntries(activeRules(db).map(r=>[r.code,{value:r.value,version:r.version}]));const sig=signature(db,weekStart,storeId),plans=[];
 for(const type of ['balanced','cost','experience']){const assigned=[],work={};let required=0,covered=0,cost=0,cross=0;for(const d of demands){required+=d.required_count;const start=dateTime(d.demand_date,d.start_time),endAt=dateTime(d.demand_date,d.end_time),duration=hours(start,endAt);const candidates=employees.map(e=>{const v=validateShift(db,{employeeId:e.id,storeId:d.store_id,role:d.role,startAt:start,endAt});const sameDay=assigned.some(a=>a.employeeId===e.id&&overlap(start,endAt,a.startAt,a.endAt));if(!v.passed||sameDay)return null;const w=weights[type],pref=e.preference.preferredShift==='morning'&&Number(d.start_time.slice(0,2))<12?1:0,score=100-e.hourly_rate*duration*w.cost/20-(work[e.id]||0)*w.fairness+pref*w.preference-(e.store_id!==d.store_id?w.cross:0);return {e,score,v};}).filter(Boolean).sort((a,b)=>b.score-a.score);for(const c of candidates.slice(0,d.required_count)){assigned.push({demandId:d.id,employeeId:c.e.id,employeeName:c.e.name,employeeCode:c.e.code,storeId:d.store_id,role:d.role,startAt:start,endAt,score:Number(c.score.toFixed(1)),reasons:[`${d.role}技能匹配`,`调剂后月工时${c.e.monthly_hours+duration}小时`,type==='cost'?'成本优先':'负荷与偏好已纳入评分']});work[c.e.id]=(work[c.e.id]||0)+duration;covered++;cost+=duration*c.e.hourly_rate+(c.e.store_id!==d.store_id?c.e.travel_cost:0);if(c.e.store_id!==d.store_id)cross++;}}
 const id=randomUUID(),coverage=Number((covered/required*100).toFixed(1)),metrics={coverage,required,covered,uncovered:required-covered,totalHours:Object.values(work).reduce((a,b)=>a+b,0),estimatedCost:Number(cost.toFixed(2)),crossStoreCount:cross,softRiskCount:assigned.reduce((n,x)=>n+x.reasons.length-3,0)};transaction(db,()=>{db.prepare('INSERT INTO schedule_plans VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,type,storeId,weekStart,'generated',j(metrics),j(rules),sig,type==='balanced'?'覆盖、成本、工时公平综合最优':type==='cost'?'优先降低加班、跨店和交通成本':'优先满足员工偏好并均衡工时',now(),null);const q=db.prepare('INSERT INTO schedule_plan_shifts VALUES(?,?,?,?,?,?,?,?,?,?)');for(const x of assigned)q.run(randomUUID(),id,x.demandId,x.employeeId,x.storeId,x.role,x.startAt,x.endAt,x.score,j(x.reasons));});plans.push(getPlan(db,id));}return plans;}
export function getPlan(db,id){const p=db.prepare('SELECT * FROM schedule_plans WHERE id=?').get(id);if(!p)return null;return {...p,metrics:parseJson(p.metrics_json,{}),ruleSnapshot:parseJson(p.rule_snapshot_json,{}),shifts:db.prepare('SELECT s.*,e.name employee_name,e.code employee_code,st.name store_name FROM schedule_plan_shifts s JOIN employees e ON e.id=s.employee_id JOIN stores st ON st.id=s.store_id WHERE s.plan_id=? ORDER BY s.start_at,e.code').all(id).map(x=>({...x,reasons:parseJson(x.reasons_json,[])}))};}
export function confirmPlan(db,id){const p=getPlan(db,id);if(!p)throw err('排班方案不存在',404);if(signature(db,p.week_start,p.store_id)!==p.data_signature)throw err('员工、请假、班次或规则已变化，请重新生成方案',409,'STALE_PLAN');transaction(db,()=>{const q=db.prepare('INSERT INTO shifts VALUES(?,?,?,?,?,?,?,?,?,?,?)');for(const x of p.shifts)q.run(randomUUID(),x.employee_id,x.store_id,x.role,x.start_at,x.end_at,'agent_plan','confirmed',id,now(),now());db.prepare("UPDATE schedule_plans SET status='confirmed',confirmed_at=? WHERE id=?").run(now(),id);});return {plan:getPlan(db,id),shifts:listShifts(db,p.week_start,new Date(new Date(p.week_start+'T00:00:00Z').getTime()+6*86400000).toISOString().slice(0,10),p.store_id)};}
export function listShifts(db,start,end,storeId){let sql='SELECT sh.*,e.name employee_name,e.code employee_code,s.name store_name FROM shifts sh JOIN employees e ON e.id=sh.employee_id JOIN stores s ON s.id=sh.store_id WHERE date(sh.start_at) BETWEEN ? AND ?',args=[start,end];if(storeId){sql+=' AND sh.store_id=?';args.push(storeId)}return db.prepare(sql+' ORDER BY sh.start_at,e.code').all(...args);}
export function saveShift(db,b,id=randomUUID()){const validation=validateShift(db,b,id);if(!validation.passed)throw Object.assign(err('班次违反硬性规则',409,'HARD_RULE_CONFLICT'),{details:validation});if(validation.softConflicts.length&&!String(b.overrideReason||'').trim())throw Object.assign(err('存在软规则风险，请填写调整原因',409,'SOFT_RULE_CONFIRMATION_REQUIRED'),{details:validation});const before=db.prepare('SELECT * FROM shifts WHERE id=?').get(id)||null;transaction(db,()=>{if(before)db.prepare('UPDATE shifts SET employee_id=?,store_id=?,role=?,start_at=?,end_at=?,updated_at=? WHERE id=?').run(b.employeeId,b.storeId,b.role,b.startAt,b.endAt,now(),id);else db.prepare('INSERT INTO shifts VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,b.employeeId,b.storeId,b.role,b.startAt,b.endAt,'manual','confirmed',null,now(),now());db.prepare('INSERT INTO shift_adjustments VALUES(?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),id,before?'update':'create',j(before),j(b),j(validation.hardConflicts),j(validation.softConflicts),b.overrideReason||'',b.operator||'演示主管',now());db.prepare('INSERT INTO rule_validation_logs VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),'shift',id,1,j([]),j(validation.softConflicts),j(Object.fromEntries(activeRules(db).map(r=>[r.code,r.version]))),now());});return {shift:db.prepare('SELECT * FROM shifts WHERE id=?').get(id),validation};}
